# Generated by Django 4.0 on 2022-01-02 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('BestOfferEnabled', models.BooleanField(default=True)),
                ('AutoPayEnabled', models.BooleanField(default=True)),
                ('CategoryID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('CategoryLevel', models.PositiveSmallIntegerField()),
                ('CategoryName', models.CharField(blank=True, max_length=100, null=True)),
                ('LeafCategory', models.BooleanField(blank=True, null=True)),
                ('CategoryParentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Categorias_Ebay.category')),
            ],
        ),
    ]
