# Generated by Django 4.0 on 2022-01-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categorias_Ebay', '0002_alter_category_categoryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='AutoPayEnabled',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='BestOfferEnabled',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
